; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:layer1-teensy40]
platform = teensy
board = teensy40
framework = arduino
build_src_filter = +<layer1/>
build_flags = -I include
monitor_speed = 115200

[env:layer1-calibrate]
platform = teensy
board = teensy40
framework = arduino
build_src_filter = +<layer1-calibrate/>
build_flags = -I include
monitor_speed = 115200

[env:layer1-serial-debug]
platform = teensy
board = teensy40
framework = arduino
build_src_filter = +<layer1-serial-debug/>
monitor_speed = 115200

[env:layer2-serial-debug]
platform = teensy
board = teensy40
framework = arduino
build_src_filter = +<layer2-serial-debug/>
monitor_speed = 115200

[env:layer2-teensy40]
platform = teensy
board = teensy40
framework = arduino
build_src_filter = +<layer2/>
monitor_speed = 115200

[env:layer3-seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
build_src_filter = +<layer3/>
monitor_speed = 115200