import math

# ------------------------------
# Simple 2D Vector
# ------------------------------
class Vec2:
    def __init__(self, x=0.0, y=0.0):
        self.x = float(x)
        self.y = float(y)

    def __add__(self, b):
        return Vec2(self.x + b.x, self.y + b.y)

    def __sub__(self, b):
        return Vec2(self.x - b.x, self.y - b.y)

    def __mul__(self, s):
        return Vec2(self.x * s, self.y * s)

    def normalize(self):
        length = math.sqrt(self.x * self.x + self.y * self.y)
        if length == 0:
            return Vec2(0, 0)
        return Vec2(self.x / length, self.y / length)


# ------------------------------
# Cone Generator (same logic as C++)
# ------------------------------
class Cone:
    def __init__(self):
        # Match your original semantics (units: cm)
        self.cameraPos = Vec2(0, 15.8)
        self.resolution = 400
        self.range = 350.0
        self.approximateConeRadius = 1.5
        self.coneStartPos = Vec2(0, 17)

        self.targetPoints = []
        self.conePoints = []

    def generate_targets(self):
        self.targetPoints.clear()
        for i in range(self.resolution):
            x = i * self.range / self.resolution
            self.targetPoints.append(Vec2(x, 0))

    def generate_cone(self):
        self.conePoints.clear()
        self.conePoints.append(self.coneStartPos)

        for i in range(1, self.resolution):
            prev = self.conePoints[i - 1]

            pointToCamera = self.cameraPos - prev
            pointToTarget = self.targetPoints[i] - prev

            a1 = math.atan2(pointToTarget.y, pointToTarget.x)
            a2 = math.atan2(pointToCamera.y, pointToCamera.x)

            angle = (a1 - a2) / 2.0
            angle = math.pi / 2.0 - angle

            dx = pointToTarget.x * math.cos(angle) - pointToTarget.y * math.sin(angle)
            dy = pointToTarget.x * math.sin(angle) + pointToTarget.y * math.cos(angle)

            direction = Vec2(dx, dy).normalize()
            direction = direction * (self.approximateConeRadius / self.resolution)

            self.conePoints.append(prev + direction)


# ------------------------------
# Export to OpenSCAD
# ------------------------------
def export_to_scad(cone: Cone, filename="cone.scad", fn=200):
    """
    Generates an OpenSCAD file that:
      - defines a 'points' array for the 2D profile (radius vs height)
      - uses rotate_extrude() to form a solid of revolution
    """

    # Build 2D profile in X–Y plane:
    # x = radius, y = height
    # We also close the profile back to the axis at top.
    pts = []

    start = cone.conePoints[0]
    end = cone.conePoints[-1]

    # Start on the axis at the bottom height
    pts.append([0.0, start.y])

    # Side profile
    for p in cone.conePoints:
        pts.append([p.x, p.y])

    # Close back to axis at the top
    pts.append([0.0, end.y])

    with open(filename, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by cone_to_scad.py\n")
        f.write("// Units: cm (as per your original code)\n\n")

        # Optional: scale to mm if you like
        f.write("// To work in mm, uncomment the 'scale([10,10,10])' line below.\n\n")

        f.write("points = [\n")
        for x, y in pts:
            f.write(f"  [{x:.6f}, {y:.6f}],\n")
        f.write("];\n\n")

        f.write("// Profile is in X-Y plane: X = radius, Y = height.\n")
        f.write("// rotate_extrude sweeps around the Z axis; Y becomes Z in 3D.\n\n")
        f.write("// Uncomment this to scale cm → mm:\n")
        f.write("// scale([10, 10, 10])\n")

        f.write("rotate_extrude($fn = %d)\n" % fn)
        f.write("    polygon(points);\n")

    print(f"Wrote OpenSCAD file: {filename}")


# ------------------------------
# Main
# ------------------------------
if __name__ == "__main__":
    cone = Cone()

    # tweak these if you want:
    cone.resolution = 400
    cone.range = 200
    cone.cameraPos.y = 95.058/10
    cone.approximateConeRadius = 1.5
    cone.coneStartPos.y = (170.25-3)/10

    cone.generate_targets()
    cone.generate_cone()

    export_to_scad(cone, "cone.scad", fn=200)
