(part "OKL-T_6-W12P-C"
    (packageRef "OKLT6W12PC")
    (interface
        (port "1" (symbPinId 1) (portName "ON/OFF_CONTROL") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VIN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GROUND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VOUT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SENSE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "TRIM") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GROUND_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NO_CONNECTION_1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "SEQUENCE") (portType INOUT))
        (port "10" (symbPinId 10) (portName "POWER_GOOD_OUT") (portType INOUT))
        (port "11" (symbPinId 11) (portName "NO_CONNECTION_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "NO_CONNECTION_3") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "580-OKL-T/6-W12P-C")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Power-Solutions/OKL-T-6-W12P-C?qs=CxV9Ey7RZVdXGDAP%2FweYNg%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "OKL-T/6-W12P-C")
    (property "Description" "MURATA POWER SOLUTIONS - OKL-T/6-W12P-C - DC-DC CONVERTER, 0.591V TO 5.5V, MODULE")
    (property "Datasheet_Link" "https://www.murata.com/products/productdata/8807038255134/okl-t6-w12.pdf?1583754815000")
    (property "symbolName1" "OKL-T_6-W12P-C")
)
