(part "TC33X-2-104E"
    (packageRef "TC33X2104E")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-TC33X-2-104E")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/TC33X-2-104E?qs=2hAPiALdQ0llyX8B3WfcDg%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "TC33X-2-104E")
    (property "Description" "Trimmer Resistors - SMD 3MM 100KOHMS 25% 0.1WATT OPEN FRM")
    (property "Datasheet_Link" "https://www.bourns.com/docs/Product-Datasheets/TC33.pdf")
    (property "symbolName1" "TC33X-2-104E")
)
